# Generated by Django 4.2.30 on 2026-05-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ssafydataimportlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssafy_data_import_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawssafydata',
            name='import_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ssafy_data', to='notices.ssafydataimportlog'),
        ),
    ]
