# Generated by Django 6.0.4 on 2026-05-13 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RawSsafyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_html', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='collected', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['source_type', 'status'], name='sync_rawssa_source__4b3458_idx'), models.Index(fields=['collected_at'], name='sync_rawssa_collect_e224a0_idx')],
            },
        ),
    ]
