# Generated by Django 6.0.4 on 2026-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljoblog',
            name='crawler_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crawljoblog',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
