# Generated by Django 4.2.30 on 2026-05-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_crawljoblog_crawler_mode_crawljoblog_skipped_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljoblog',
            name='academic_rule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawljoblog',
            name='no_schedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawljoblog',
            name='notice_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
