# Generated by Django 4.2.30 on 2026-06-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0005_rawssafydata_ocr_boxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='sync.rawssafydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'read_at'], name='sync_userno_user_id_3ae43a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usernoticereadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'raw_data'), name='unique_user_notice_read_status'),
        ),
    ]
