# Generated by Django 4.2.30 on 2026-05-14 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('apple', 'Apple')], max_length=30)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.TextField(blank=True)),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='oauthaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_oauth_provider_user'),
        ),
        migrations.AddConstraint(
            model_name='oauthaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_oauth_provider'),
        ),
    ]
