# Generated by Django 4.2.30 on 2026-06-04 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oauthaccount_oauthaccount_unique_oauth_provider_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('campus', models.CharField(blank=True, choices=[('서울', '서울'), ('대전', '대전'), ('광주', '광주'), ('구미', '구미'), ('부울경', '부울경')], max_length=30, null=True)),
                ('track', models.CharField(blank=True, choices=[('Java', 'Java'), ('Python', 'Python'), ('Embedded', 'Embedded'), ('Mobile', 'Mobile'), ('Data', 'Data'), ('AI', 'AI'), ('기타', '기타')], max_length=50, null=True)),
                ('class_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('notice_notification_enabled', models.BooleanField(default=True)),
                ('schedule_reminder_enabled', models.BooleanField(default=True)),
                ('ai_question_notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
