# Generated by Django 4.2.30 on 2026-05-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('OCR', 'OCR'), ('CRAWLING', 'Crawling'), ('MANUAL', 'Manual'), ('AI', 'AI')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('MONTHLY_TEST', 'Monthly Test'), ('SUBJECT_TEST', 'Subject Test'), ('PROJECT', 'Project'), ('LECTURE', 'Lecture'), ('APPLICATION', 'Application'), ('PERSONAL', 'Personal')], max_length=50)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_at', 'deadline_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_events', to='calendar.scheduleevent')),
            ],
        ),
    ]
