# Generated by Django 4.2.30 on 2026-05-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduleevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='notices.rawssafydata'),
        ),
        migrations.AddConstraint(
            model_name='userscheduleevent',
            constraint=models.UniqueConstraint(fields=('user', 'schedule_event'), name='unique_user_schedule_event'),
        ),
    ]
