# Generated by Django 4.2.30 on 2026-06-11 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_scheduleevent_owner'),
        ('calendar', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_calendar_events', to='schedules.scheduleevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hiddencalendarevent',
            constraint=models.UniqueConstraint(fields=('user', 'schedule_event'), name='unique_hidden_calendar_event'),
        ),
    ]
