# Generated by Django 4.2.30 on 2026-06-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleevent_owner'),
        ('calendar', '0003_hiddencalendarevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheduleevent',
            name='schedule_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_events', to='schedules.scheduleevent'),
        ),
    ]
