# Generated by Django 4.2.30 on 2026-06-24 16:20

from django.db import migrations, models


def copy_hidden_events_to_user_schedule_events(apps, schema_editor):
    HiddenCalendarEvent = apps.get_model('calendar', 'HiddenCalendarEvent')
    UserScheduleEvent = apps.get_model('calendar', 'UserScheduleEvent')
    for hidden in HiddenCalendarEvent.objects.all().iterator():
        link, _created = UserScheduleEvent.objects.get_or_create(
            user_id=hidden.user_id,
            schedule_event_id=hidden.schedule_event_id,
        )
        if not link.is_hidden:
            link.is_hidden = True
            link.save(update_fields=['is_hidden'])


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_alter_userscheduleevent_schedule_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduleevent',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_is_all_day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscheduleevent',
            name='override_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(copy_hidden_events_to_user_schedule_events, migrations.RunPython.noop),
    ]
