# Generated by Django 4.2.30 on 2026-06-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_userscheduleevent_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userscheduleevent',
            index=models.Index(fields=['user', 'is_hidden'], name='calendar_us_user_id_0c97dd_idx'),
        ),
    ]
