# Generated by Django 4.2.30 on 2026-05-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession'),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='raw_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='notices.rawssafydata'),
        ),
        migrations.AddField(
            model_name='aichatreference',
            name='ai_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_references', to='ai.aidocument'),
        ),
        migrations.AddField(
            model_name='aichatreference',
            name='chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='ai.chatmessage'),
        ),
    ]
