# Generated by Codex on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_rawssafydata_ocr_boxes'),
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocument',
            name='raw_data',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ai_documents',
                to='notices.rawssafydata',
            ),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='sync_raw_data',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ai_documents',
                to='sync.rawssafydata',
            ),
        ),
    ]
