# Generated by Codex on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_scheduleevent_metadata_json'),
        ('ai', '0003_aidocument_sync_raw_data_nullable_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidocument',
            name='schedule_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ai_documents',
                to='schedules.scheduleevent',
            ),
        ),
    ]
