# Generated by Django 4.2.30 on 2026-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aidocument_schedule_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='usage_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
