# Generated by Django 4.2.30 on 2026-06-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0005_chatmessage_usage_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('query_type', models.CharField(blank=True, max_length=100)),
                ('answer_policy', models.CharField(blank=True, max_length=100)),
                ('route_stage', models.CharField(blank=True, max_length=100)),
                ('failure_type', models.CharField(blank=True, max_length=100)),
                ('is_success', models.BooleanField(default=True)),
                ('retrieved_context_json', models.JSONField(blank=True, default=dict)),
                ('references_json', models.JSONField(blank=True, default=list)),
                ('usage_json', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='ai.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['created_at'], name='ai_aipipeli_created_034326_idx'),
                    models.Index(fields=['intent'], name='ai_aipipeli_intent_184f80_idx'),
                    models.Index(fields=['answer_policy'], name='ai_aipipeli_answer__e28803_idx'),
                    models.Index(fields=['route_stage'], name='ai_aipipeli_route_s_369394_idx'),
                    models.Index(fields=['is_success'], name='ai_aipipeli_is_succ_6d2c7f_idx'),
                ],
            },
        ),
    ]
