# Generated by Django 4.2.30 on 2026-06-22 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0006_aipipelinerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(default='auto', max_length=50)),
                ('quality_score', models.FloatField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('retrieved_count', models.PositiveIntegerField(default=0)),
                ('is_fallback', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('is_no_context', models.BooleanField(default=False)),
                ('feedback_type', models.CharField(default='none', max_length=30)),
                ('feedback_note', models.TextField(blank=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='aiqualitylog',
            name='pipeline_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_log', to='ai.aipipelinerun'),
        ),
        migrations.AddField(
            model_name='aiqualitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_quality_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiqualitylog',
            index=models.Index(fields=['created_at'], name='ai_aiqualit_created_915bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='aiqualitylog',
            index=models.Index(fields=['evaluator'], name='ai_aiqualit_evaluat_37de9f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiqualitylog',
            index=models.Index(fields=['feedback_type'], name='ai_aiqualit_feedbac_e2732e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiqualitylog',
            index=models.Index(fields=['quality_score'], name='ai_aiqualit_quality_51b759_idx'),
        ),
        migrations.AddIndex(
            model_name='aiqualitylog',
            index=models.Index(fields=['is_error'], name='ai_aiqualit_is_erro_0fe0b2_idx'),
        ),
    ]
