# Generated by Django 4.2.30 on 2026-06-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('subject', 'Subject evaluation'), ('monthly', 'Monthly evaluation')], max_length=20)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('retake', 'Retake'), ('absent', 'Absent'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['evaluation_type', 'round_number', 'id'],
                'indexes': [models.Index(fields=['user', 'evaluation_type'], name='risk_evalua_user_id_c97d34_idx'), models.Index(fields=['scheduled_at'], name='risk_evalua_schedul_b8920b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.UniqueConstraint(fields=('user', 'evaluation_type', 'round_number'), name='unique_user_evaluation_round'),
        ),
    ]
