# Generated by Django 4.2.30 on 2026-06-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_evaluationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='max_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['user', 'subject_name'], name='risk_evalua_user_id_37e4df_idx'),
        ),
    ]
