# Generated by Django 4.2.30 on 2026-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
