# Generated by Django 6.0.4 on 2026-05-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('event_type', models.CharField(default='notice', max_length=50)),
                ('source_type', models.CharField(default='notice', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='sync.rawssafydata')),
            ],
            options={
                'ordering': ['start_at', 'id'],
                'indexes': [models.Index(fields=['start_at', 'end_at'], name='schedules_s_start_a_2d2b1a_idx'), models.Index(fields=['event_type'], name='schedules_s_event_t_7b3692_idx'), models.Index(fields=['source_type', 'source_id'], name='schedules_s_source__c6d321_idx')],
            },
        ),
    ]
